default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: todoster_development
test:
  <<: *default
  database: todoster_test

production:
  <<: *default
  database: todoster_production
  # username: todo
  # password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
